const fs = require("node:fs");
const path = require("node:path");

// reads .env from the project root and writes the app's config file so
// end users never have to touch environment variables.
const envPath = path.join(__dirname, "..", ".env");
const configPath = path.join(__dirname, "..", "src", "config.generated.js");

function findEnvFile() {
  if (fs.existsSync(envPath)) return { file: envPath, env: loadEnv(envPath) };
  return { file: null, env: {} };
}

function loadEnv(filePath) {
  const result = {};
  if (!fs.existsSync(filePath)) return result;
  for (const line of fs.readFileSync(filePath, "utf8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    result[key] = value;
  }
  return result;
}

function main() {
  const { file, env } = findEnvFile();

  const supabaseUrl = env.SUPABASE_URL;
  const supabaseAnonKey = env.SUPABASE_ANON_KEY;
  const defaultExtensions = (env.SYNC_EXTENSIONS ?? ".fountain")
    .split(",")
    .map((e) => e.trim())
    .filter(Boolean);

  if (!supabaseUrl || !supabaseAnonKey) {
    console.warn(
      "[beatsync] warning: SUPABASE_URL / SUPABASE_ANON_KEY not found in " +
        envPath +
        " — the app will not be able to connect until you add them.",
    );
  } else {
    console.log("[beatsync] read config from " + file);
  }

  const content =
    `// auto-generated by scripts/inject-config.js — do not edit by hand.\n` +
    `// this file is written at build/start time from a .env file so that\n` +
    `// end users of the packaged app never need to configure anything.\n` +
    `module.exports = {\n` +
    `  supabaseUrl: ${JSON.stringify(supabaseUrl ?? "")},\n` +
    `  supabaseAnonKey: ${JSON.stringify(supabaseAnonKey ?? "")},\n` +
    `  defaultExtensions: ${JSON.stringify(defaultExtensions)},\n` +
    `};\n`;

  fs.writeFileSync(configPath, content);
  console.log("[beatsync] wrote " + configPath);
}

main();
